### ISSUE TITLE
Tap failed with code 1 and error message: "invalid literal for int() 

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-referral-saasquatch#5]
This occurred in the Stitch production environment using version 1.0.0 of tap-referral-saasquatch:

2018-05-23 16:12:48,879Z    tap - Traceback (most recent call last):
2018-05-23 16:12:48,880Z    tap -   File "tap-env/bin/tap-referral-saasquatch", line 11, in <module>
2018-05-23 16:12:48,880Z    tap -     sys.exit(main())
2018-05-23 16:12:48,880Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 211, in main
2018-05-23 16:12:48,880Z    tap -     raise exc
2018-05-23 16:12:48,881Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 208, in main
2018-05-23 16:12:48,881Z    tap -     main_impl()
2018-05-23 16:12:48,881Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 203, in main_impl
2018-05-23 16:12:48,881Z    tap -     do_sync()
2018-05-23 16:12:48,882Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 189, in do_sync
2018-05-23 16:12:48,882Z    tap -     sync_entity("users", ["id", "accountId"])
2018-05-23 16:12:48,882Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 178, in sync_entity
2018-05-23 16:12:48,882Z    tap -     transformed_row = transform_row(entity, row)
2018-05-23 16:12:48,883Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 157, in transform_row
2018-05-23 16:12:48,883Z    tap -     return {field: transform_field(entity, field, value) for field, value in row.items()}
2018-05-23 16:12:48,883Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 157, in <dictcomp>
2018-05-23 16:12:48,883Z    tap -     return {field: transform_field(entity, field, value) for field, value in row.items()}
2018-05-23 16:12:48,884Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 152, in transform_field
2018-05-23 16:12:48,884Z    tap -     return TRANSFORMS[entity][field](value)
2018-05-23 16:12:48,884Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_referral_saasquatch/__init__.py", line 131, in transform_timestamp
2018-05-23 16:12:48,885Z    tap -     return utils.strftime(datetime.datetime.utcfromtimestamp(int(value) * 0.001))
2018-05-23 16:12:48,885Z    tap - ValueError: invalid literal for int() with base 10: '**.***.***.***'

Numerical values in the final line were redacted with asterisks.

**Comment by hayward-saasquatch** [comment]
Looks like this is a result of the returned export CSV being improperly parsed. 

In situations where a field (like a name) includes a comma in it (e.g. `James, jr`) the fields are being incorrectly split at that point, rather than correctly at the end of the string.

This can be traced back to here in the code: https://github.com/singer-io/tap-referral-saasquatch/blob/master/tap_referral_saasquatch/__init__.py#L116

**Comment by hayward-saasquatch** [comment]
@dylan-stitch our team has made a pull request to address this issue: https://github.com/singer-io/tap-referral-saasquatch/pull/6
